=== serpi90/hadoop-installer/Installer/src/main/resources/configuration.dtd
<!ELEMENT configuration (defaults,nodes,ssh,files)>
<!ELEMENT defaults (username,installationDirectory)>
<!ELEMENT nodes (node+)>
<!ELEMENT node (hostname,port?,username?,installationDirectory?)>
<!ELEMENT hostname (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT installationDirectory (#PCDATA)>
<!ELEMENT ssh (sshKeyFile?)>
<!ELEMENT sshKeyFile (#PCDATA)>
<!ELEMENT files (hadoop,java7)>
<!ELEMENT hadoop (#PCDATA)>
<!ELEMENT java7 (#PCDATA)>

=== serpi90/hadoop-installer/Installer/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<configuration>
    <defaults>
        <username>hadoop</username>
        <installationDirectory>/home/hadoop/hadoop</installationDirectory>
    </defaults>
    <nodes>
        <node>
            <hostname>localhost</hostname>
            <port>22</port>
        </node>
    </nodes>
    <ssh>
        <sshKeyFile>/home/julian/tesis/ssh_keys/id_rsa</sshKeyFile>
    </ssh>
    <files>
	<hadoop>hadoop-2.5.1.tar.gz</hadoop>
	<java7>jre-7u67-linux-x64.tar.gz</java7>
    </files>
</configuration>
